apiVersion: v1
kind: Service
metadata:
  name: ftgo-tram-cdc-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    svc: ftgo-tram-cdc-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ftgo-tram-cdc-service
  labels:
    application: ftgo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: ftgo-tram-cdc-service
    spec:
      containers:
      - name: ftgo-tram-cdc-service
        image: eventuateio/eventuate-tram-cdc-mysql-service:0.20.0.M11
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: httpport
        command: ["bash", "-c", "java -Dsun.net.inetaddr.ttl=30 -jar *.jar" ]
        env:
          - name: JAVA_OPTS
            value: "-Dsun.net.inetaddr.ttl=30"
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: ftgo-kafka:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: ftgo-zookeeper:2181
          - name: EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE
            value: eventuate-local
          - name: EVENTUATE_CDC_PIPELINE_PIPELINE1_READER
            value: reader1
          - name: EVENTUATE_CDC_PIPELINE_PIPELINE2_TYPE
            value: eventuate-tram
          - name: EVENTUATE_CDC_PIPELINE_PIPELINE2_READER
            value: reader1
          - name: EVENTUATE_CDC_READER_READER1_TYPE
            value: mysql-binlog
          - name: EVENTUATE_CDC_READER_READER1_DATASOURCEURL
            value: jdbc:mysql://ftgo-mysql:3306/eventuate
          - name: EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME
            value: mysqluser
          - name: EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD
            value: mysqlpw
          - name: EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME
            value: com.mysql.jdbc.Driver
          - name: EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH
            value: /eventuate/cdc/leader/eventuatelocal
          - name: EVENTUATE_CDC_READER_READER1_BINLOGCLIENTID
            value: "1"
          - name: EVENTUATE_CDC_READER_READER1_CDCDBUSERNAME
            value: root
          - name: EVENTUATE_CDC_READER_READER1_CDCDBPASSWORD
            value: rootpassword
          - name: EVENTUATE_CDC_READER_READER1_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC
            value: "false"
          - name: EVENTUATE_CDC_READER_READER1_MYSQLBINLOGCLIENTNAME
            value: ClientEventuateLocal
          - name: EVENTUATE_CDC_READER_READER1_OFFSETSTORAGETOPICNAME
            value: db.history.eventuate.local
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
---
